CREATE TABLE player_tracking_log
(
  id SERIAL NOT NULL,
  player_name VARCHAR(100),
  player_id BIGINT,
  did_not_play BOOLEAN DEFAULT FALSE,
  team VARCHAR(20),
  win BOOLEAN,
  game_date DATE,
  game_id BIGINT,
  min INTEGER,
  dist FLOAT,
  spd FLOAT, 
  tchs INTEGER, 
  pass INTEGER, 
  ast INTEGER, 
  sast INTEGER, 
  ftast INTEGER, 
  dfgm INTEGER, 
  dfg FLOAT, 
  orbc INTEGER, 
  drbc INTEGER, 
  rbc INTEGER, 
  fg FLOAT, 
  cfgm INTEGER, 
  cfga INTEGER, 
  cfg FLOAT, 
  ufgm INTEGER, 
  ufga INTEGER, 
  ufg FLOAT
);
