CREATE TABLE team_tracking_log
(
  id SERIAL NOT NULL,
  team VARCHAR(100),
  win BOOLEAN,
  game_date DATE,
  game_id BIGINT,
  min INTEGER,
  dist FLOAT,
  spd FLOAT, 
  tchs INTEGER, 
  pass INTEGER, 
  ast INTEGER, 
  sast INTEGER, 
  ftast INTEGER, 
  dfgm INTEGER, 
  dfga INTEGER, 
  dfg FLOAT, 
  orbc INTEGER, 
  drbc INTEGER, 
  rbc INTEGER, 
  fg FLOAT, 
  cfgm INTEGER, 
  cfga INTEGER, 
  cfg FLOAT, 
  ufgm INTEGER, 
  ufga INTEGER, 
  ufg FLOAT
);
